version: '3.8'

services:
  app:
    build: .
    ports:
      - "9929:9929"
    volumes:
      - ./backend/hub_test.db:/app/backend/hub.db
      - ./backend/static_test:/app/backend/static
      - ./downloads_test:/app/backend/library/media_downloader
    env_file:
      - ./backend/.env
    environment:
      - PORT=9929
      - ALLOW_REGISTRATION=true
      - SECRET_KEY=test_secure_random_secret_here
    restart: unless-stopped
